# Generated by Django 5.0 on 2023-12-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل')),
                ('copy_right', models.TextField(verbose_name='متن کپی رایت سایت')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما سایت')),
                ('map', models.CharField(max_length=200, verbose_name='نقشه')),
                ('site_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.image', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': ' footer',
                'verbose_name_plural': 'footers',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='عنوان')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.image', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('site_logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.image', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'header',
                'verbose_name_plural': 'headers',
            },
        ),
    ]
